"""Audit / compliance dossier export (Markdown + JSON)."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.models.results import VerificationResult
from app.services.policy import PolicyDecision


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def build_audit_payload(
    result: VerificationResult,
    *,
    decision: PolicyDecision | None = None,
    policy: dict[str, Any] | None = None,
    timestamp: str | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Structured audit record suitable for JSON export and compliance review."""
    ts = timestamp or _utc_now_iso()
    payload: dict[str, Any] = {
        "schema": "truthgraph.audit.v1",
        "timestamp": ts,
        "claim": result.claim,
        "verdict": result.verdict,
        "confidence": result.confidence,
        "matched_keywords": list(result.matched_keywords),
        "reasons": list(result.reasons),
        "supporting_evidence": [e.model_dump() for e in result.supporting_evidence],
        "contradicting_evidence": [e.model_dump() for e in result.contradicting_evidence],
        "subclaims": [s.model_dump() for s in result.subclaims],
        "breakdown": result.breakdown.model_dump() if result.breakdown else None,
        "meta": dict(result.meta),
    }
    if decision is not None:
        payload["decision"] = decision.decision
        payload["policy_id"] = decision.policy_id
        payload["policy_reasons"] = list(decision.reasons)
        payload["policy_thresholds"] = dict(decision.thresholds)
    elif policy is not None:
        payload["policy"] = policy
    if extra:
        payload["extra"] = extra
    return payload


def render_audit_markdown(payload: dict[str, Any]) -> str:
    """Human-readable Markdown audit report."""
    lines: list[str] = [
        "# TruthGraph Audit Dossier",
        "",
        f"- **Timestamp (UTC):** {payload.get('timestamp', '')}",
        f"- **Schema:** `{payload.get('schema', 'truthgraph.audit.v1')}`",
        f"- **Claim:** {payload.get('claim', '')}",
        f"- **Verdict:** `{payload.get('verdict', '')}`",
        f"- **Confidence:** {payload.get('confidence', '')}",
    ]
    if "decision" in payload:
        lines.append(f"- **Decision:** `{payload['decision']}`")
        lines.append(f"- **Policy:** `{payload.get('policy_id', '')}`")
    lines.append("")
    lines.append("## Reasons")
    reasons = payload.get("reasons") or []
    if reasons:
        for r in reasons:
            lines.append(f"- {r}")
    else:
        lines.append("- (none)")
    if payload.get("policy_reasons"):
        lines.append("")
        lines.append("## Policy reasons")
        for r in payload["policy_reasons"]:
            lines.append(f"- {r}")
    lines.append("")
    lines.append("## Supporting evidence")
    supporting = payload.get("supporting_evidence") or []
    if supporting:
        for e in supporting:
            lines.append(
                f"- **{e.get('source', '?')}** (reliability={e.get('reliability', '?')}): "
                f"{e.get('text', '')}"
            )
    else:
        lines.append("- (none)")
    lines.append("")
    lines.append("## Contradicting evidence")
    contradicting = payload.get("contradicting_evidence") or []
    if contradicting:
        for e in contradicting:
            lines.append(
                f"- **{e.get('source', '?')}** (reliability={e.get('reliability', '?')}): "
                f"{e.get('text', '')}"
            )
    else:
        lines.append("- (none)")
    subclaims = payload.get("subclaims") or []
    if subclaims:
        lines.append("")
        lines.append("## Sub-claims")
        for s in subclaims:
            lines.append(
                f"- [{s.get('verdict')} @ {s.get('confidence')}] {s.get('text')}"
            )
    if payload.get("matched_keywords"):
        lines.append("")
        lines.append("## Matched keywords")
        lines.append(", ".join(payload["matched_keywords"]))
    if payload.get("policy_thresholds"):
        lines.append("")
        lines.append("## Policy thresholds")
        lines.append("```json")
        lines.append(json.dumps(payload["policy_thresholds"], indent=2))
        lines.append("```")
    if payload.get("breakdown"):
        lines.append("")
        lines.append("## Score breakdown")
        lines.append("```json")
        lines.append(json.dumps(payload["breakdown"], indent=2))
        lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("_Generated by TruthGraph — deterministic evidence gate. No LLM judge._")
    lines.append("")
    return "\n".join(lines)


def export_audit(
    result: VerificationResult,
    out_dir: str | Path,
    *,
    basename: str = "audit",
    decision: PolicyDecision | None = None,
    extra: dict[str, Any] | None = None,
) -> dict[str, Path]:
    """Write Markdown + JSON audit files; return paths."""
    directory = Path(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    payload = build_audit_payload(result, decision=decision, extra=extra)
    json_path = directory / f"{basename}.json"
    md_path = directory / f"{basename}.md"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    md_path.write_text(render_audit_markdown(payload), encoding="utf-8")
    return {"json": json_path, "markdown": md_path}
